icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
idle_bg = "#0d0d0d"
idle_fg = "#efefef"
info_bg = "#b086f9"
info_fg = "#0d0d0d"
good_bg = "#9ee050"
good_fg = "#0d0d0d"
warning_bg = "#ffa53f"
warning_fg = "#0d0d0d"
critical_bg = "#ff2a70"
critical_fg = "#0d0d0d"
separator = ""

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %R:%S"

